### PR TITLE
add missing settings hints

### PR DESCRIPTION
**Pull request by jrappen**

### CODE REVIEW

**Comment by Ultra-Instinct-05** [comment]
@jrappen Can you also add `gtk_enable_key_translation` as well, while you are at it ? (Introduced in 4103)
Reference: https://github.com/sublimehq/sublime_text/issues/4024#issuecomment-831017864

**Comment by jrappen** [comment]
@Ultra-Instinct-05 maybe you can add that in another PR while @FichteFoll merges this one, I deleted my fork and don't have time for this in the next couple of days

**Comment by FichteFoll** [comment]
Thanks. Some of the wording is suboptimal, but it's obviously still better than not having them in. I'm also surprised I can still merge this despite the original branch being deleted.

@Ultra-Instinct-05 if you could make a follow-up PR, that would be much appreciated. I struggled to find the time to work on the next PD release over the past weeks and didn't get it done on this weekend either, but I'll try again next week.

**Comment by jrappen** [comment]
@FichteFoll It's just 14 lines, you could've just closed this and written it yourself. Whatever works.

**Comment by FichteFoll** [comment]
I could have, but I also could have gone to bed an hour ago. It's all about compromises. :wink:

**Pull request merged**
